### ISSUE TITLE
Adding library dependency to akka-persistence-shared-inmemory screws up the test classpath

### ISSUE THREAD

**Issue by hseeberger** [jdgoldie/akka-persistence-shared-inmemory#6]
To reproduce, create a fresh project directory and add the following `build.sbt`:

```
scalaVersion := "2.11.6"
resolvers += Resolver.bintrayRepo("jdgoldie", "maven")
libraryDependencies ++= List(
//  "com.github.jdgoldie" %% "akka-persistence-shared-inmemory" % "1.0.16",
  "com.typesafe.akka" %% "akka-testkit" % "2.3.9" % "test"
)
```

Now start sbt and execute `test:console`. Then evaluate `import akka.testkit.TestProbe`. Everything is fine.

Finally remove the comment in `build.sbt`, reload the sbt session and try again to import `TestProbe` in the REPL:

```
scala> import akka.testkit.TestProbe
<console>:7: error: object TestProbe is not a member of package akka.testkit
```

**Comment by hseeberger** [comment]
The only strange things I have noticed in the build are:
- Why depend on scalac-scoverage-plugin_2.11 in `compile` configuration (https://github.com/jdgoldie/akka-persistence-shared-inmemory/blob/master/build.sbt#L42)? 
- Maybe remove `withSources() withJavadoc()` from the library dependencies, because this introduces a lot of respective dependencies in the generated POM.

**Comment by jdgoldie** [comment]
That's probably a mistake.  (scoverage dependency).

**Comment by jdgoldie** [comment]
The issue should be resolved.  Version number is still 1.0.16.
