### ISSUE TITLE
Reset journal between single node tests

### ISSUE THREAD

**Issue by Unisay** [jdgoldie/akka-persistence-shared-inmemory#7]
My test class extends `akka.testkit.TestKit` and contains several tests.

I would like to be able to reset journal so that each test starts from scratch (currently journal is kept between tests).

First idea was to send `JournalProtocol.DeleteMessagesTo(persistenceId, toSeqNr, true)` before each test, but this is `private[persistence]`

Could you please suggest a solution?

Thanks.

**Comment by Unisay** [comment]
So here is my solution:

```scala
import akka.persistence.inmem.journal.InMemoryJournal

object TestJournal {

  case object Truncate

}

/**
 * Journal for testing - supports truncation
 */
class TestJournal extends InMemoryJournal {

  import agordo.TestJournal._

  val receiveTruncate: PartialFunction[Any, Unit] = {
    case Truncate =>
      mm.clear()
      log.debug("Journal cleared")
  }

  override def receive = receiveTruncate orElse super.receive

}
```

**Comment by jdgoldie** [comment]
Hey Yuriy, 

Completely missed this issue until just now.  I generally handle this situation by using a new id for each test.  Your solution also works well.  I don't see a drawback to adding in that message.

**Comment by Unisay** [comment]
Joshua,

I just realized that same trick wouldn't work for the `InMemorySnapshotStore` since `receive` is final :(

Didn't quite get the idea with new id for each test, could you please clarify what id do you mean?

**Comment by Unisay** [comment]
BTW, would you consider merging a PR with such feature if I do it?

**Comment by jdgoldie** [comment]
You can use a different PersistentId value for each test.  If you're event-sourcing, this is generally the unique ID/primary key of the particular aggregate root the actor is managing.  I can see how there are cases where clearing the journal is a better approach.

I'd be glad to look at a pull request to add this feature.

**Comment by Unisay** [comment]
Joshua,

I have created a pull request that uses other (more simpler) approach to Journal / SnapshotStore truncation - exposes truncate() operation for the underlying hashmap via companion object.

This works well for Journal, however, for the SnapshotStore several tests fail:
- they only fail when run as `sbt test`
- if run from IDE without sbt - it doesn't fail.

The failure is subtle and somehow related to timing, look:
```
expected 
LoadSnapshotResult(Some(SelectedSnapshot(SnapshotMetadata(p-8,14,1433270708272),s-4)),9223372036854775807), 
found 
LoadSnapshotResult(Some(SelectedSnapshot(SnapshotMetadata(p-8,14,1433270707599),s-4)),9223372036854775807)
```

The only difference is the timestamp of `SnapshotMetadata`. 
I tried to debug it but without luck (so far) as my knowledge/understanding of persistence internal protocols is limited yet.

I was wondering how to make the test do not depend on System.currentTimeMillis to make it more deterministic...

Do you have any ideas how moving hasmap to the companion object could affect timestamp of snapshot metadata?

**Comment by Unisay** [comment]
Ok, I have fixed the problem by cleaning snapshot store before each test.

**Comment by jdgoldie** [comment]
Thanks. I will try to look at it in the next week.

Yuriy Lazarev wrote:
